#!/bin/sh

set -e

su -c "dbus-send --type=method_call --dest=org.hildon.eventfeed /org/hildon/eventfeed org.hildon.eventfeed.addRefreshAction string:/opt/cutetubeevents/bin/cutetubeevents" - user

exit 0
